// Comprehensive list of all countries with ISO codes, flags, and phone number lengths
export interface Country {
  name: string;
  code: string;
  flag: string;
  maxDigits: number;
  minDigits: number;
}

export const allCountries: Country[] = [
  { name: "Afghanistan", code: "+93", flag: "🇦🇫", minDigits: 9, maxDigits: 9 },
  { name: "Albania", code: "+355", flag: "🇦🇱", minDigits: 9, maxDigits: 9 },
  { name: "Algeria", code: "+213", flag: "🇩🇿", minDigits: 9, maxDigits: 9 },
  { name: "Andorra", code: "+376", flag: "🇦🇩", minDigits: 6, maxDigits: 6 },
  { name: "Angola", code: "+244", flag: "🇦🇴", minDigits: 9, maxDigits: 9 },
  { name: "Antigua and Barbuda", code: "+1-268", flag: "🇦🇬", minDigits: 7, maxDigits: 7 },
  { name: "Argentina", code: "+54", flag: "🇦🇷", minDigits: 10, maxDigits: 10 },
  { name: "Armenia", code: "+374", flag: "🇦🇲", minDigits: 8, maxDigits: 8 },
  { name: "Australia", code: "+61", flag: "🇦🇺", minDigits: 9, maxDigits: 9 },
  { name: "Austria", code: "+43", flag: "🇦🇹", minDigits: 10, maxDigits: 13 },
  { name: "Azerbaijan", code: "+994", flag: "🇦🇿", minDigits: 9, maxDigits: 9 },
  { name: "Bahamas", code: "+1-242", flag: "🇧🇸", minDigits: 7, maxDigits: 7 },
  { name: "Bahrain", code: "+973", flag: "🇧🇭", minDigits: 8, maxDigits: 8 },
  { name: "Bangladesh", code: "+880", flag: "🇧🇩", minDigits: 10, maxDigits: 10 },
  { name: "Barbados", code: "+1-246", flag: "🇧🇧", minDigits: 7, maxDigits: 7 },
  { name: "Belarus", code: "+375", flag: "🇧🇾", minDigits: 9, maxDigits: 9 },
  { name: "Belgium", code: "+32", flag: "🇧🇪", minDigits: 9, maxDigits: 9 },
  { name: "Belize", code: "+501", flag: "🇧🇿", minDigits: 7, maxDigits: 7 },
  { name: "Benin", code: "+229", flag: "🇧🇯", minDigits: 8, maxDigits: 8 },
  { name: "Bhutan", code: "+975", flag: "🇧🇹", minDigits: 8, maxDigits: 8 },
  { name: "Bolivia", code: "+591", flag: "🇧🇴", minDigits: 8, maxDigits: 8 },
  { name: "Bosnia and Herzegovina", code: "+387", flag: "🇧🇦", minDigits: 8, maxDigits: 8 },
  { name: "Botswana", code: "+267", flag: "🇧🇼", minDigits: 7, maxDigits: 8 },
  { name: "Brazil", code: "+55", flag: "🇧🇷", minDigits: 10, maxDigits: 11 },
  { name: "Brunei", code: "+673", flag: "🇧🇳", minDigits: 7, maxDigits: 7 },
  { name: "Bulgaria", code: "+359", flag: "🇧🇬", minDigits: 9, maxDigits: 9 },
  { name: "Burkina Faso", code: "+226", flag: "🇧🇫", minDigits: 8, maxDigits: 8 },
  { name: "Burundi", code: "+257", flag: "🇧🇮", minDigits: 8, maxDigits: 8 },
  { name: "Cabo Verde", code: "+238", flag: "🇨🇻", minDigits: 7, maxDigits: 7 },
  { name: "Cambodia", code: "+855", flag: "🇰🇭", minDigits: 9, maxDigits: 9 },
  { name: "Cameroon", code: "+237", flag: "🇨🇲", minDigits: 9, maxDigits: 9 },
  { name: "Canada", code: "+1", flag: "🇨🇦", minDigits: 10, maxDigits: 10 },
  { name: "Central African Republic", code: "+236", flag: "🇨🇫", minDigits: 8, maxDigits: 8 },
  { name: "Chad", code: "+235", flag: "🇹🇩", minDigits: 8, maxDigits: 8 },
  { name: "Chile", code: "+56", flag: "🇨🇱", minDigits: 9, maxDigits: 9 },
  { name: "China", code: "+86", flag: "🇨🇳", minDigits: 11, maxDigits: 11 },
  { name: "Colombia", code: "+57", flag: "🇨🇴", minDigits: 10, maxDigits: 10 },
  { name: "Comoros", code: "+269", flag: "🇰🇲", minDigits: 7, maxDigits: 7 },
  { name: "Congo (Congo-Brazzaville)", code: "+242", flag: "🇨🇬", minDigits: 9, maxDigits: 9 },
  { name: "Costa Rica", code: "+506", flag: "🇨🇷", minDigits: 8, maxDigits: 8 },
  { name: "Croatia", code: "+385", flag: "🇭🇷", minDigits: 9, maxDigits: 9 },
  { name: "Cuba", code: "+53", flag: "🇨🇺", minDigits: 8, maxDigits: 8 },
  { name: "Cyprus", code: "+357", flag: "🇨🇾", minDigits: 8, maxDigits: 8 },
  { name: "Czechia (Czech Republic)", code: "+420", flag: "🇨🇿", minDigits: 9, maxDigits: 9 },
  { name: "Democratic Republic of the Congo", code: "+243", flag: "🇨🇩", minDigits: 9, maxDigits: 9 },
  { name: "Denmark", code: "+45", flag: "🇩🇰", minDigits: 8, maxDigits: 8 },
  { name: "Djibouti", code: "+253", flag: "🇩🇯", minDigits: 6, maxDigits: 6 },
  { name: "Dominica", code: "+1-767", flag: "🇩🇲", minDigits: 7, maxDigits: 7 },
  { name: "Dominican Republic", code: "+1-809", flag: "🇩🇴", minDigits: 7, maxDigits: 7 },
  { name: "Ecuador", code: "+593", flag: "🇪🇨", minDigits: 9, maxDigits: 9 },
  { name: "Egypt", code: "+20", flag: "🇪🇬", minDigits: 9, maxDigits: 10 },
  { name: "El Salvador", code: "+503", flag: "🇸🇻", minDigits: 8, maxDigits: 8 },
  { name: "Equatorial Guinea", code: "+240", flag: "🇬🇶", minDigits: 9, maxDigits: 9 },
  { name: "Eritrea", code: "+291", flag: "🇪🇷", minDigits: 7, maxDigits: 7 },
  { name: "Estonia", code: "+372", flag: "🇪🇪", minDigits: 8, maxDigits: 8 },
  { name: "Eswatini (Swaziland)", code: "+268", flag: "🇸🇿", minDigits: 8, maxDigits: 8 },
  { name: "Ethiopia", code: "+251", flag: "🇪🇹", minDigits: 9, maxDigits: 9 },
  { name: "Fiji", code: "+679", flag: "🇫🇯", minDigits: 7, maxDigits: 7 },
  { name: "Finland", code: "+358", flag: "🇫🇮", minDigits: 6, maxDigits: 12 },
  { name: "France", code: "+33", flag: "🇫🇷", minDigits: 9, maxDigits: 9 },
  { name: "Gabon", code: "+241", flag: "🇬🇦", minDigits: 8, maxDigits: 8 },
  { name: "Gambia", code: "+220", flag: "🇬🇲", minDigits: 7, maxDigits: 7 },
  { name: "Georgia", code: "+995", flag: "🇬🇪", minDigits: 9, maxDigits: 9 },
  { name: "Germany", code: "+49", flag: "🇩🇪", minDigits: 10, maxDigits: 13 },
  { name: "Ghana", code: "+233", flag: "🇬🇭", minDigits: 9, maxDigits: 9 },
  { name: "Greece", code: "+30", flag: "🇬🇷", minDigits: 10, maxDigits: 10 },
  { name: "Grenada", code: "+1-473", flag: "🇬🇩", minDigits: 7, maxDigits: 7 },
  { name: "Guatemala", code: "+502", flag: "🇬🇹", minDigits: 8, maxDigits: 8 },
  { name: "Guinea", code: "+224", flag: "🇬🇳", minDigits: 8, maxDigits: 9 },
  { name: "Guinea-Bissau", code: "+245", flag: "🇬🇼", minDigits: 7, maxDigits: 7 },
  { name: "Guyana", code: "+592", flag: "🇬🇾", minDigits: 7, maxDigits: 7 },
  { name: "Haiti", code: "+509", flag: "🇭🇹", minDigits: 8, maxDigits: 8 },
  { name: "Honduras", code: "+504", flag: "🇭🇳", minDigits: 8, maxDigits: 8 },
  { name: "Hungary", code: "+36", flag: "🇭🇺", minDigits: 9, maxDigits: 9 },
  { name: "Iceland", code: "+354", flag: "🇮🇸", minDigits: 7, maxDigits: 7 },
  { name: "India", code: "+91", flag: "🇮🇳", minDigits: 10, maxDigits: 10 },
  { name: "Indonesia", code: "+62", flag: "🇮🇩", minDigits: 9, maxDigits: 11 },
  { name: "Iran", code: "+98", flag: "🇮🇷", minDigits: 10, maxDigits: 10 },
  { name: "Iraq", code: "+964", flag: "🇮🇶", minDigits: 10, maxDigits: 10 },
  { name: "Ireland", code: "+353", flag: "🇮🇪", minDigits: 9, maxDigits: 9 },
  { name: "Israel", code: "+972", flag: "🇮🇱", minDigits: 9, maxDigits: 9 },
  { name: "Italy", code: "+39", flag: "🇮🇹", minDigits: 9, maxDigits: 10 },
  { name: "Jamaica", code: "+1-876", flag: "🇯🇲", minDigits: 7, maxDigits: 7 },
  { name: "Japan", code: "+81", flag: "🇯🇵", minDigits: 10, maxDigits: 10 },
  { name: "Jordan", code: "+962", flag: "🇯🇴", minDigits: 9, maxDigits: 9 },
  { name: "Kazakhstan", code: "+7", flag: "🇰🇿", minDigits: 10, maxDigits: 10 },
  { name: "Kenya", code: "+254", flag: "🇰🇪", minDigits: 9, maxDigits: 9 },
  { name: "Kiribati", code: "+686", flag: "🇰🇮", minDigits: 5, maxDigits: 5 },
  { name: "Kuwait", code: "+965", flag: "🇰🇼", minDigits: 8, maxDigits: 8 },
  { name: "Kyrgyzstan", code: "+996", flag: "🇰🇬", minDigits: 9, maxDigits: 9 },
  { name: "Laos", code: "+856", flag: "🇱🇦", minDigits: 10, maxDigits: 10 },
  { name: "Latvia", code: "+371", flag: "🇱🇻", minDigits: 8, maxDigits: 8 },
  { name: "Lebanon", code: "+961", flag: "🇱🇧", minDigits: 8, maxDigits: 8 },
  { name: "Lesotho", code: "+266", flag: "🇱🇸", minDigits: 8, maxDigits: 8 },
  { name: "Liberia", code: "+231", flag: "🇱🇷", minDigits: 8, maxDigits: 8 },
  { name: "Libya", code: "+218", flag: "🇱🇾", minDigits: 9, maxDigits: 10 },
  { name: "Liechtenstein", code: "+423", flag: "🇱🇮", minDigits: 7, maxDigits: 7 },
  { name: "Lithuania", code: "+370", flag: "🇱🇹", minDigits: 8, maxDigits: 8 },
  { name: "Luxembourg", code: "+352", flag: "🇱🇺", minDigits: 9, maxDigits: 9 },
  { name: "Madagascar", code: "+261", flag: "🇲🇬", minDigits: 9, maxDigits: 9 },
  { name: "Malawi", code: "+265", flag: "🇲🇼", minDigits: 8, maxDigits: 9 },
  { name: "Malaysia", code: "+60", flag: "🇲🇾", minDigits: 9, maxDigits: 9 },
  { name: "Maldives", code: "+960", flag: "🇲🇻", minDigits: 7, maxDigits: 7 },
  { name: "Mali", code: "+223", flag: "🇲🇱", minDigits: 8, maxDigits: 8 },
  { name: "Malta", code: "+356", flag: "🇲🇹", minDigits: 8, maxDigits: 8 },
  { name: "Marshall Islands", code: "+692", flag: "🇲🇭", minDigits: 7, maxDigits: 7 },
  { name: "Mauritania", code: "+222", flag: "🇲🇷", minDigits: 8, maxDigits: 8 },
  { name: "Mauritius", code: "+230", flag: "🇲🇺", minDigits: 7, maxDigits: 8 },
  { name: "Mexico", code: "+52", flag: "🇲🇽", minDigits: 10, maxDigits: 10 },
  { name: "Micronesia", code: "+691", flag: "🇫🇲", minDigits: 7, maxDigits: 7 },
  { name: "Moldova", code: "+373", flag: "🇲🇩", minDigits: 8, maxDigits: 8 },
  { name: "Monaco", code: "+377", flag: "🇲🇨", minDigits: 8, maxDigits: 8 },
  { name: "Mongolia", code: "+976", flag: "🇲🇳", minDigits: 8, maxDigits: 8 },
  { name: "Montenegro", code: "+382", flag: "🇲🇪", minDigits: 8, maxDigits: 8 },
  { name: "Morocco", code: "+212", flag: "🇲🇦", minDigits: 9, maxDigits: 9 },
  { name: "Mozambique", code: "+258", flag: "🇲🇿", minDigits: 9, maxDigits: 9 },
  { name: "Myanmar (Burma)", code: "+95", flag: "🇲🇲", minDigits: 9, maxDigits: 9 },
  { name: "Namibia", code: "+264", flag: "🇳🇦", minDigits: 9, maxDigits: 9 },
  { name: "Nauru", code: "+674", flag: "🇳🇷", minDigits: 7, maxDigits: 7 },
  { name: "Nepal", code: "+977", flag: "🇳🇵", minDigits: 10, maxDigits: 10 },
  { name: "Netherlands", code: "+31", flag: "🇳🇱", minDigits: 9, maxDigits: 9 },
  { name: "New Zealand", code: "+64", flag: "🇳🇿", minDigits: 8, maxDigits: 9 },
  { name: "Nicaragua", code: "+505", flag: "🇳🇮", minDigits: 8, maxDigits: 8 },
  { name: "Niger", code: "+227", flag: "🇳🇪", minDigits: 8, maxDigits: 8 },
  { name: "Nigeria", code: "+234", flag: "🇳🇬", minDigits: 10, maxDigits: 10 },
  { name: "North Korea", code: "+850", flag: "🇰🇵", minDigits: 10, maxDigits: 10 },
  { name: "North Macedonia", code: "+389", flag: "🇲🇰", minDigits: 8, maxDigits: 8 },
  { name: "Norway", code: "+47", flag: "🇳🇴", minDigits: 8, maxDigits: 8 },
  { name: "Oman", code: "+968", flag: "🇴🇲", minDigits: 8, maxDigits: 8 },
  { name: "Pakistan", code: "+92", flag: "🇵🇰", minDigits: 10, maxDigits: 10 },
  { name: "Palau", code: "+680", flag: "🇵🇼", minDigits: 7, maxDigits: 7 },
  { name: "Palestine", code: "+970", flag: "🇵🇸", minDigits: 9, maxDigits: 9 },
  { name: "Panama", code: "+507", flag: "🇵🇦", minDigits: 8, maxDigits: 8 },
  { name: "Papua New Guinea", code: "+675", flag: "🇵🇬", minDigits: 8, maxDigits: 8 },
  { name: "Paraguay", code: "+595", flag: "🇵🇾", minDigits: 9, maxDigits: 9 },
  { name: "Peru", code: "+51", flag: "🇵🇪", minDigits: 9, maxDigits: 9 },
  { name: "Philippines", code: "+63", flag: "🇵🇭", minDigits: 10, maxDigits: 10 },
  { name: "Poland", code: "+48", flag: "🇵🇱", minDigits: 9, maxDigits: 9 },
  { name: "Portugal", code: "+351", flag: "🇵🇹", minDigits: 9, maxDigits: 9 },
  { name: "Qatar", code: "+974", flag: "🇶🇦", minDigits: 8, maxDigits: 8 },
  { name: "Romania", code: "+40", flag: "🇷🇴", minDigits: 9, maxDigits: 10 },
  { name: "Russia", code: "+7", flag: "🇷🇺", minDigits: 10, maxDigits: 10 },
  { name: "Rwanda", code: "+250", flag: "🇷🇼", minDigits: 9, maxDigits: 9 },
  { name: "Saint Kitts and Nevis", code: "+1-869", flag: "🇰🇳", minDigits: 7, maxDigits: 7 },
  { name: "Saint Lucia", code: "+1-758", flag: "🇱🇨", minDigits: 7, maxDigits: 7 },
  { name: "Saint Vincent and the Grenadines", code: "+1-784", flag: "🇻🇨", minDigits: 7, maxDigits: 7 },
  { name: "Samoa", code: "+685", flag: "🇼🇸", minDigits: 7, maxDigits: 7 },
  { name: "San Marino", code: "+378", flag: "🇸🇲", minDigits: 6, maxDigits: 10 },
  { name: "São Tomé and Príncipe", code: "+239", flag: "🇸🇹", minDigits: 7, maxDigits: 7 },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦", minDigits: 9, maxDigits: 9 },
  { name: "Senegal", code: "+221", flag: "🇸🇳", minDigits: 9, maxDigits: 9 },
  { name: "Serbia", code: "+381", flag: "🇷🇸", minDigits: 8, maxDigits: 10 },
  { name: "Seychelles", code: "+248", flag: "🇸🇨", minDigits: 7, maxDigits: 7 },
  { name: "Sierra Leone", code: "+232", flag: "🇸🇱", minDigits: 8, maxDigits: 8 },
  { name: "Singapore", code: "+65", flag: "🇸🇬", minDigits: 8, maxDigits: 8 },
  { name: "Slovakia", code: "+421", flag: "🇸🇰", minDigits: 9, maxDigits: 9 },
  { name: "Slovenia", code: "+386", flag: "🇸🇮", minDigits: 8, maxDigits: 9 },
  { name: "Solomon Islands", code: "+677", flag: "🇸🇧", minDigits: 7, maxDigits: 7 },
  { name: "Somalia", code: "+252", flag: "🇸🇴", minDigits: 8, maxDigits: 9 },
  { name: "South Africa", code: "+27", flag: "🇿🇦", minDigits: 9, maxDigits: 9 },
  { name: "South Korea", code: "+82", flag: "🇰🇷", minDigits: 9, maxDigits: 11 },
  { name: "South Sudan", code: "+211", flag: "🇸🇸", minDigits: 9, maxDigits: 9 },
  { name: "Spain", code: "+34", flag: "🇪🇸", minDigits: 9, maxDigits: 9 },
  { name: "Sri Lanka", code: "+94", flag: "🇱🇰", minDigits: 9, maxDigits: 9 },
  { name: "Sudan", code: "+249", flag: "🇸🇩", minDigits: 9, maxDigits: 9 },
  { name: "Suriname", code: "+597", flag: "🇸🇷", minDigits: 7, maxDigits: 7 },
  { name: "Sweden", code: "+46", flag: "🇸🇪", minDigits: 7, maxDigits: 9 },
  { name: "Switzerland", code: "+41", flag: "🇨🇭", minDigits: 9, maxDigits: 9 },
  { name: "Syria", code: "+963", flag: "🇸🇾", minDigits: 9, maxDigits: 9 },
  { name: "Taiwan", code: "+886", flag: "🇹🇼", minDigits: 9, maxDigits: 9 },
  { name: "Tajikistan", code: "+992", flag: "🇹🇯", minDigits: 9, maxDigits: 9 },
  { name: "Tanzania", code: "+255", flag: "🇹🇿", minDigits: 9, maxDigits: 9 },
  { name: "Thailand", code: "+66", flag: "🇹🇭", minDigits: 9, maxDigits: 9 },
  { name: "Timor-Leste", code: "+670", flag: "🇹🇱", minDigits: 8, maxDigits: 8 },
  { name: "Togo", code: "+228", flag: "🇹🇬", minDigits: 8, maxDigits: 8 },
  { name: "Tonga", code: "+676", flag: "🇹🇴", minDigits: 7, maxDigits: 7 },
  { name: "Trinidad and Tobago", code: "+1-868", flag: "🇹🇹", minDigits: 7, maxDigits: 7 },
  { name: "Tunisia", code: "+216", flag: "🇹🇳", minDigits: 8, maxDigits: 8 },
  { name: "Turkey", code: "+90", flag: "🇹🇷", minDigits: 10, maxDigits: 10 },
  { name: "Turkmenistan", code: "+993", flag: "🇹🇲", minDigits: 8, maxDigits: 8 },
  { name: "Tuvalu", code: "+688", flag: "🇹🇻", minDigits: 6, maxDigits: 6 },
  { name: "Uganda", code: "+256", flag: "🇺🇬", minDigits: 9, maxDigits: 9 },
  { name: "Ukraine", code: "+380", flag: "🇺🇦", minDigits: 9, maxDigits: 9 },
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪", minDigits: 9, maxDigits: 9 },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧", minDigits: 10, maxDigits: 10 },
  { name: "United States", code: "+1", flag: "🇺🇸", minDigits: 10, maxDigits: 10 },
  { name: "Uruguay", code: "+598", flag: "🇺🇾", minDigits: 8, maxDigits: 8 },
  { name: "Uzbekistan", code: "+998", flag: "🇺🇿", minDigits: 9, maxDigits: 9 },
  { name: "Vanuatu", code: "+678", flag: "🇻🇺", minDigits: 7, maxDigits: 7 },
  { name: "Vatican City", code: "+39", flag: "🇻🇦", minDigits: 6, maxDigits: 10 },
  { name: "Venezuela", code: "+58", flag: "🇻🇪", minDigits: 10, maxDigits: 10 },
  { name: "Vietnam", code: "+84", flag: "🇻🇳", minDigits: 9, maxDigits: 10 },
  { name: "Yemen", code: "+967", flag: "🇾🇪", minDigits: 9, maxDigits: 9 },
  { name: "Zambia", code: "+260", flag: "🇿🇲", minDigits: 9, maxDigits: 9 },
  { name: "Zimbabwe", code: "+263", flag: "🇿🇼", minDigits: 9, maxDigits: 9 },
];

// Sort countries alphabetically by name
export const sortedCountries = [...allCountries].sort((a, b) => {
  const nameA = a.name.toLowerCase().trim();
  const nameB = b.name.toLowerCase().trim();
  return nameA.localeCompare(nameB, undefined, { sensitivity: 'base', numeric: true });
});

// Get phone rules for a country
export function getPhoneRule(countryName: string): { min: number; max: number } {
  const country = allCountries.find(c => c.name === countryName);
  if (country) {
    return { min: country.minDigits, max: country.maxDigits };
  }
  // Default fallback: use maximum digits any country has (13 for Germany/Austria)
  return { min: 5, max: 13 };
}
